name: Build and Push Docker Image

on:
  push:
    branches:
      - 'main'
    paths:
      - 'Dockerfile'
      - 'entrypoint.sh'
      - 'config/**'
      - '.github/workflows/ci.yaml'
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set tag name
        id: tag_name
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "tag=latest" >> $GITHUB_OUTPUT
          else
            echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          fi
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/usa-reddragon/kiri:${{ steps.tag_name.outputs.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Extract minor version from tag, ie v1.2.3 -> v1.2
        id: minor_version
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          echo "minor_version=${GITHUB_REF#refs/tags/}" | sed 's/\.[^.]*$//' >> $GITHUB_OUTPUT
      - name: Extract major version from tag, ie v1.2.3 -> v1
        id: major_version
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          echo "major_version=${GITHUB_REF#refs/tags/}" | sed 's/\.[^.]*$//' | sed 's/\.[^.]*$//' >> $GITHUB_OUTPUT
      - name: Build and push minor version
        uses: docker/build-push-action@v4
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          push: true
          tags: ghcr.io/usa-reddragon/kiri:${{ steps.minor_version.outputs.minor_version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build and push major version
        uses: docker/build-push-action@v4
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          push: true
          tags: ghcr.io/usa-reddragon/kiri:${{ steps.major_version.outputs.major_version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      # Also tag the repo with the minor and major version
      - name: Tag minor version
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --local user.name "${GITHUB_ACTOR}"
          git tag -d ${{ steps.minor_version.outputs.minor_version }} || true
          git tag ${{ steps.minor_version.outputs.minor_version }}
      - name: Tag major version
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --local user.name "${GITHUB_ACTOR}"
          git tag -d ${{ steps.major_version.outputs.major_version }} || true
          git tag ${{ steps.major_version.outputs.major_version }}
      - name: Push tags
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          git push --delete origin ${{ steps.minor_version.outputs.minor_version }} || true
          git push --delete origin ${{ steps.major_version.outputs.major_version }} || true
          git push origin ${{ steps.minor_version.outputs.minor_version }}
          git push origin ${{ steps.major_version.outputs.major_version }}
